/**
 * Small HUD and book icons (16 x 16): Resolve's flame, Grace's drop of light,
 * the heart scale with its two pans, pity's tear (a shape, not only a colour,
 * bible §1.6), justice's pan, and a word card. Keys `icon-<name>`.
 *
 * Owner: team D (art). Pure data. The UI may scale them by whole numbers.
 */

import { image, type Bitmap } from './bitmap';
import { rows, type Palette } from './pixelmap';

const PAL: Palette = {
  k: 0x1a120c,
  r: 0xe0703a,
  R: 0xa83a1a,
  y: 0xf6d36a,
  w: 0xfff4d2,
  g: 0xf2e6a6,
  G: 0xb8a65a,
  b: 0x6fa3d8,
  B: 0x3a6a9e,
  j: 0xc08a3a,
  J: 0x7a5420,
  p: 0xe9dfc6,
  P: 0xb8a57e,
  i: 0x2b2118,
};

const FLAME = rows(`
.......k........
......kyk.......
......kyk.......
.....kyyrk......
.....kyrrk......
....kyyrrrk.....
....kyrrrRk.....
...kyrrwrrRk....
...kyrwwyrRk....
..kyrrwwyyrRk...
..kyrwwyyyrRk...
..kyrwyyyyrRk...
..kRrrwyyrrRk...
...kRrrrrrRk....
....kkRRRRk.....
......kkkk......
`);

const DROP = rows(`
.......k........
.......k........
......kgk.......
......kgk.......
.....kggGk......
.....kwggGk.....
....kwwgggGk....
....kwgggggk....
...kwggggggGk...
...kwggggggGk...
...kggggggggk...
...kGgggggggk...
....kGggggGk....
.....kGGGGk.....
......kkkk......
................
`);

const TEAR = rows(`
.......k........
......kbk.......
......kbk.......
.....kbbBk......
.....kwbbBk.....
....kwbbbbBk....
....kwbbbbbk....
...kwbbbbbbBk...
...kbbbbbbbBk...
...kbbbbbbbBk...
...kBbbbbbbBk...
....kBbbbbBk....
.....kBBBBk.....
......kkkk......
................
................
`);

const PAN = rows(`
................
.......kk.......
......kjjk......
......kjjk......
.....k.kk.k.....
....k..kk..k....
...k...kk...k...
..k....kk....k..
.kkkkkkkkkkkkkk.
.kjjjjjjjjjjjjk.
..kjjjjjjjjjjk..
...kJjjjjjjJk...
....kkJJJJkk....
......kkkk......
................
................
`);

const SCALE = rows(`
.......kk.......
.......kk.......
.kkkkkkkkkkkkkk.
.k.....kk.....k.
.k.....kk.....k.
k.k....kk....k.k
k.k....kk....k.k
kbbk...kk...kjjk
kkkk...kk...kkkk
.......kk.......
.......kk.......
.......kk.......
.....kkkkkk.....
....kjjjjjjk....
....kkkkkkkk....
................
`);

const CARD = rows(`
..kkkkkkkkkkk...
..kpppppppppPk..
..kpiiiiipppPk..
..kpppppppppPk..
..kpiiiiiiipPk..
..kpppppppppPk..
..kpiiiiipppPk..
..kpppppppppPk..
..kppppyypppPk..
..kpppyyyyppPk..
..kppppyypppPk..
..kpppppppppPk..
..kPPPPPPPPPPk..
..kkkkkkkkkkkk..
................
................
`);

export function iconBitmaps(): Bitmap[] {
  return [
    image('icon-flame', FLAME, PAL),
    image('icon-drop', DROP, PAL),
    image('icon-tear', TEAR, PAL),
    image('icon-pan', PAN, PAL),
    image('icon-scale', SCALE, PAL),
    image('icon-card', CARD, PAL),
  ];
}
