/**
 * The three beasts of Canto I (bible §5.3–§5.5): the spotted panther, the lion
 * with his head held high, the gaunt she-wolf. Drawn facing right; the left
 * frames are mirrors. They are never hurt (bible §0.4 rule 5).
 *
 * Owner: team D (art). Pure data.
 */

import { mirror, pad, replaceFrom, rows, shift, type Palette } from '../pixelmap';

export const BEAST_FRAME = 32;

export const PANTHER_PALETTE: Palette = {
  k: 0x1c140c,
  t: 0xc9a15a,
  T: 0x8e6a34,
  l: 0xe6cf98,
  d: 0x3a2810,
  e: 0xe8d040,
  n: 0x5a3a2a,
  w: 0xf2ead8,
};

export const LION_PALETTE: Palette = {
  k: 0x1e130a,
  t: 0xc58e45,
  T: 0x8d5e28,
  l: 0xe2c07c,
  M: 0x4e2c12,
  m: 0x7a4a1e,
  e: 0xf0d050,
  n: 0x3a2214,
  w: 0xf2ead8,
  r: 0x7a1a14,
};

export const WOLF_PALETTE: Palette = {
  k: 0x101012,
  G: 0x4a4a4e,
  g: 0x7c7c7e,
  l: 0xa6a6a2,
  e: 0xd85a30,
  n: 0x202022,
  w: 0xe8e4dc,
};

const PANTHER = rows(`
.k.............................
kTk............................
kTk.....................kk.kk..
.kTk...................kTkkTk..
..kTk.................kttttttk.
...kTkkkkkkkkkkkkkkkkkttttettk.
....kttdttdttdttdttdtttttttttnk
....ktdtttttdtttttdttttttlllkk.
....kttdttdtttdttdtttttlllk....
....kTttttttttttttttttTllk.....
.....kTtttdtttttdtttttTlk......
.....kTTTkkkkkkkkkkkTTTk.......
.....kTtk.........kTtk.........
.....kTtk.........kTtk.........
....kTTk.........kTTk..........
....kkk..........kkk...........
`);
const PANTHER_LEGS_A = rows(`
.....kTTTkkkkkkkkkkkTTTk.......
....kTtk............kTtk.......
...kTtk..............kTtk......
..kTTk................kTTk.....
..kkk..................kkk.....
`);
const PANTHER_LEGS_B = rows(`
.....kTTTkkkkkkkkkkkTTTk.......
......kTtk.......kTtk..........
......kTtk.......kTtk..........
......kTTk.......kTTk..........
......kkk........kkk...........
`);
/** The spring: stretched out, forepaws reaching. */
const PANTHER_LEAP_LEGS = rows(`
.....kTTTkkkkkkkkkkkTTTk.......
...kTTk.................kTTk...
.kTTk.....................kTk..
kkk........................kk..
...............................
`);

const LION = rows(`
......................kkkkk.....
....................kkMMMMMkk...
...................kMMmmmmmMMk..
..................kMMmttttmMMk..
..................kMmttttetmMk..
.k................kMmtttttttnk..
kMk...............kMMmtttllmk...
kMk..kkkkkkkkkkkkkMMMmtlllk.....
.kTkkttttttttttttMMMMmmkkk......
..kTtttttttttttttMMMMk..........
...ktttttttttttttMMMk...........
...kTttttttttttttTTk............
....kTTTkkkkkkkkTTTk............
....kTtk.......kTtk.............
....kTtk.......kTtk.............
...kTTk.......kTTk..............
...kkk........kkk...............
`);
const LION_LEGS_A = rows(`
....kTTTkkkkkkkkTTTk............
...kTtk..........kTtk...........
..kTtk............kTtk..........
.kTTk..............kTTk.........
.kkk................kkk.........
`);
const LION_LEGS_B = rows(`
....kTTTkkkkkkkkTTTk............
.....kTtk.....kTtk..............
.....kTtk.....kTtk..............
.....kTTk.....kTTk..............
.....kkk......kkk...............
`);
/** The roar: jaws open (the fear wave of inf01.s4). */
const LION_ROAR_HEAD = rows(`
......................kkkkk.....
....................kkMMMMMkk...
...................kMMmmmmmMMk..
..................kMMmttttmMMk..
..................kMmttttetmMk..
.k................kMmttttttkkk..
kMk...............kMMmttkwwrk...
kMk..kkkkkkkkkkkkkMMMmtkrrrk....
.kTkkttttttttttttMMMMmmkwwk.....
`);

const WOLF = rows(`
...............................
..........................k.k..
.........................kgkgk.
.k.......................kgggk.
kgk.....................kggggk.
kgk...kkkkkkkkkkkkkkkk.kgggegk.
.kgk.kGggggggggggggggkkggggggnk
..kgkGgglglglglgggggggggggkkkk.
...kGggglglglglggggggggGk......
....kGgggggggggggggggGGk.......
.....kGGkkkkkkkkkkkkGGk........
.....kGgk..........kGgk........
.....kGgk..........kGgk........
.....kGgk..........kGgk........
....kGGk..........kGGk.........
....kkk...........kkk..........
`);
const WOLF_LEGS_A = rows(`
.....kGGkkkkkkkkkkkkGGk........
....kGgk.............kGgk......
...kGgk...............kGgk.....
...kGgk...............kGgk.....
..kGGk.................kGGk....
..kkk...................kkk....
`);
const WOLF_LEGS_B = rows(`
.....kGGkkkkkkkkkkkkGGk........
......kGgk.........kGgk........
......kGgk.........kGgk........
......kGgk.........kGgk........
......kGGk.........kGGk........
......kkk..........kkk.........
`);
/** Head lowered, teeth bared: the advance "by degrees" (I 59). */
const WOLF_STALK = rows(`
...............................
...............................
.k.............................
kgk............................
kgk...kkkkkkkkkkkkkkkk.........
.kgk.kGggggggggggggggkk.k.k....
..kgkGgglglglglgggggggkkgkgk...
...kGggglglglglgggggggggggggk..
....kGggggggggggggggggggggegk..
.....kGGkkkkkkkkkkkkGGkgggggwnk
.....kGgk..........kGgkkkkkkkk.
.....kGgk..........kGgk........
.....kGgk..........kGgk........
....kGGk..........kGGk.........
....kkk...........kkk..........
`);

function beastFrame(map: readonly string[]): string[] {
  return pad(map, BEAST_FRAME, BEAST_FRAME, 'bottom', 0, -1);
}

function withMirrors(frames: Array<[string, string[]]>): Array<[string, string[]]> {
  const out: Array<[string, string[]]> = [];
  for (const [name, map] of frames) out.push([`right-${name}`, map]);
  for (const [name, map] of frames) out.push([`left-${name}`, mirror(map)]);
  return out;
}

export function pantherFrames(): Array<[string, string[]]> {
  const idle = beastFrame(PANTHER);
  const a = beastFrame(replaceFrom(PANTHER, 11, PANTHER_LEGS_A));
  const b = beastFrame(replaceFrom(PANTHER, 11, PANTHER_LEGS_B));
  const leap = shift(beastFrame(replaceFrom(PANTHER, 11, PANTHER_LEAP_LEGS)), 0, -3);
  return withMirrors([
    ['0', idle],
    ['1', a],
    ['2', b],
    ['leap', leap],
  ]);
}

export function lionFrames(): Array<[string, string[]]> {
  const idle = beastFrame(LION);
  const a = beastFrame(replaceFrom(LION, 12, LION_LEGS_A));
  const b = beastFrame(replaceFrom(LION, 12, LION_LEGS_B));
  const roar = beastFrame(replaceFrom(LION, 0, LION_ROAR_HEAD));
  const lunge = shift(beastFrame(replaceFrom(LION, 12, LION_LEGS_A)), 1, -2);
  return withMirrors([
    ['0', idle],
    ['1', a],
    ['2', b],
    ['roar', roar],
    ['lunge', lunge],
  ]);
}

export function wolfFrames(): Array<[string, string[]]> {
  const idle = beastFrame(WOLF);
  const a = beastFrame(replaceFrom(WOLF, 10, WOLF_LEGS_A));
  const b = beastFrame(replaceFrom(WOLF, 10, WOLF_LEGS_B));
  const stalk = beastFrame(WOLF_STALK);
  return withMirrors([
    ['0', idle],
    ['1', a],
    ['2', b],
    ['stalk', stalk],
  ]);
}
