import { loadStoryLibrary } from '/src/story/load';
import { planGenericLevel, planDecor } from '/src/levels/_framework/layout';
import { planAmbience } from '/src/levels/_framework/ambient';
const lib = loadStoryLibrary({ includeFixtures: true });
const id = process.argv[2] ?? 'inf05';
const sc = lib.script(id)!;
const plan = planGenericLevel(sc);
console.log('size', plan.width, plan.height, 'start', plan.start, 'mechanics', plan.mechanics.join(','));
for (const p of plan.places) console.log(`  ${p.id.padEnd(26)} ${plan.themes[p.id]} x=${p.x} y=${p.y} w=${p.w} h=${p.h} spawn=${JSON.stringify(p.spawn)}`);
for (const n of plan.npcs) console.log(`  npc ${n.speaker}@${n.place} x=${n.x} y=${n.y} talk=${n.talkable} crowd=${(n as any).crowd} tex=${(n as any).texture}`);
console.log('path', JSON.stringify(plan.path));
const decor = planDecor(plan);
console.log('decor', decor.items.filter((d) => !['grass','flower'].includes(d.kind)).map((d) => `${d.kind}@${d.x},${d.y}`).join(' '));
const amb = planAmbience(plan, decor);
console.log('ambient', JSON.stringify({ dark: amb.darkness?.zones.length, fear: amb.fear?.zones, wind: amb.wind }));
